# Generated by Django 5.1.5 on 2025-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
