# Generated by Django 5.1.5 on 2025-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='number_of_series',
            field=models.IntegerField(default=0),
        ),
    ]
